---
- name: Save Config 
  bigip_config:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    save: yes
    validate_certs: "no"
  delegate_to: localhost
...
