---
- name: Create a registration key (regkey) pool to hold individual device licenses
  bigiq_regkey_pool:
    name: "{{ regkey_pool_name }}"
    password: "{{ password }}"
    server: "{{ ansible_host }}"
    state: "{{ state }}"
    user: "{{ username }}"
    validate_certs: no
  delegate_to: localhost
...
