---
- name: Import PEM Certificate from local disk
  bigip_ssl_certificate:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ inventory_hostname }}"
      name: "domain"
      cert_content: "{{ lookup('file', 'domain.crt') }}"
      key_content: "{{ lookup('file', 'domain.key') }}"
      validate_certs: "no"
      state: "present"
  delegate_to: localhost
...
