---
- name: Manage the iApp contained in template appsvcs_integration_v2.0.004.tmpl
  bigip_iapp_template:
    user: "{{username}}"
    password: "{{password}}"
    server: "{{ inventory_hostname }}"
    content: "{{ lookup('file', 'appsvcs_integration_v2.0.004.tmpl') }}"
    state: "{{ state }}"
  delegate_to: localhost
...
