---
- name: Disable Setup Wizard 
  bigip_sys_db:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    key: "setup.run"
    value: "false"
  delegate_to: localhost
...
