---
- name: Save Config 
  bigip_command:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    commands: save sys config
    validate_certs: "no"
  delegate_to: localhost
...
